# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, verbose_name='商品名稱')),
                ('item_description', models.TextField(max_length=100, verbose_name='商品描述')),
                ('item_price', models.PositiveIntegerField(default=None, verbose_name='商品價格')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('item_url', models.CharField(default=None, max_length=200, verbose_name='商品相關連結')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcshoppings.Category', verbose_name='商品分類')),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(default=None, max_length=20)),
                ('member_account', models.CharField(default=None, max_length=8, verbose_name='登入帳號')),
                ('member_homephone', models.PositiveIntegerField(default=None, verbose_name='市內電話')),
                ('member_phone', models.PositiveIntegerField(blank=True, default=None, verbose_name='手機')),
                ('member_email', models.CharField(default=None, max_length=20, verbose_name='email')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcshoppings.member'),
        ),
    ]
