# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcshoppings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, verbose_name='商品名稱')),
                ('item_description', models.TextField(max_length=100, verbose_name='商品描述')),
                ('item_price', models.PositiveIntegerField(default=0, verbose_name='商品價格')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcshoppings.Category', verbose_name='商品分類')),
            ],
        ),
        migrations.DeleteModel(
            name='shopping_cpu',
        ),
        migrations.AddField(
            model_name='member',
            name='member_account',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='member',
            name='member_phone',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
